### ISSUE TITLE
[BUG] Cannot create tls connector: invalid peer certificate: BadEncoding

### ISSUE THREAD

**Issue by PabloGirol** [erebe/wstunnel#234] opened 2024-02-27 18:57 UTC
**Describe the bug**
While executing wstunnel a BadEncoding error appears while parsing certificates

**To Reproduce**
I dont know how to reproduce it at this exact moment

**Expected behavior**
Should create a tunnel with any address given to it as a client

**Screenshots**
![imagen](https://github.com/erebe/wstunnel/assets/47150336/d1538206-a2ca-4e34-b628-4f4b06e27ca8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox v123
 - Version 

**Additional context**
It never works, my language and region is Spanish/Spain and I've recompiled with different certificates encoding and I could not make it work

**Comment by erebe** [comment] 2024-03-04 16:10
Would you mind sharing the certificate of the server ?

**Comment by alou-S** [comment] 2024-03-07 18:40
@erebe One of my "clients" has the exact same error occurring on his PC. But I can't reproduce it myself on Windows or Linux, and none of my other clients report the same issue. 
I can provide a backtrace if needed but here is the reply of `openssl s_client -connect ${WSTUNNEL_SERVER_IP}:${PORT} -showcerts`

[openssl.log](https://github.com/erebe/wstunnel/files/14528627/openssl.log)

If anything else is required please do ask

**Comment by erebe** [comment] 2024-03-08 08:20
Woud you mind trying this pre-release https://github.com/erebe/wstunnel/releases/tag/v9.2.4 and let me know if it fix your issue.

My guess is that there is an invalid certificate in the system store of the host/machine.

**Comment by alou-S** [comment] 2024-03-09 10:56
Should that be used on the client too? Hosting the server with that didn't fix the client's error.

**Comment by erebe** [comment] 2024-03-09 13:23
it should be used client side yes, sorry. On the server it will not change anything

**Comment by PabloGirol** [comment] 2024-03-12 19:57
> Would you mind sharing the certificate of the server ?

I don't know why this would be useful, as this happens with either the server active or not.

I tried the prerelease you mentioned and the tunnel now seems to work, the error is still there but it wont keep wstunnel from running

And yeah, your theory is correct as it seems, my windows, somehow, has an invalid certificate in the system store
![imagen](https://github.com/erebe/wstunnel/assets/47150336/81426483-4bc9-4227-8390-ac68e91829f1)

**Comment by erebe** [comment] 2024-03-17 09:38
> > Would you mind sharing the certificate of the server ?
> 
> I don't know why this would be useful, as this happens with either the server active or not.
> 
I read too quickly the issue :see_no_evil: 


The fix is released in version 9.2.4 https://github.com/erebe/wstunnel/releases/tag/v9.2.4

**Closed by erebe** 2024-03-17 09:38 UTC
