### ISSUE TITLE
crash with mTLS (wireguard over wstunnel)

### ISSUE THREAD

**Issue by blutz1982** [erebe/wstunnel#385] opened 2024-12-14 12:54 UTC
## Describe the bug
I created PKI according to the instructions https://github.com/erebe/wstunnel/blob/main/docs/using_mtls.md and got a wstunnel client crash

## To Reproduce
1. Create a PKI using these instructions https://github.com/erebe/wstunnel/blob/main/docs/using_mtls.md
2. Start the wstunnel server
```sh
wstunnel server wss://0.0.0.0:443 --restrict-to=localhost:51820 --tls-certificate=wstunnel-server.cert.pem --tls-private-key=wstunnel-server.pem --tls-client-ca-certs=ca.cert.pem --log-lvl=DEBUG
```

3. Start the wstunnel client

```sh
./wstunnel client -L 'udp://51820:localhost:51820?timeout_sec=0' --tls-private-key=wstunnel-client-1.pem --tls-certificate=wstunnel-client-1.cert.pem wss://194.87.44.164:443 --log-lvl=DEBUG
```

After running wireguard (or having any network traffic from the client-side on upd/51820, for example sending a udp packet using netcat) - the wstunnel client crashes with an error
```
thread 'tokio-runtime-worker' panicked at src/tunnel/transport/websocket.rs:260:37:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7043a53568aa - <unknown>
   1:     0x7043a504bc5b - <unknown>
   2:     0x7043a532bc52 - <unknown>
   3:     0x7043a5358219 - <unknown>
   4:     0x7043a5357a06 - <unknown>
   5:     0x7043a5358e11 - <unknown>
   6:     0x7043a535854a - <unknown>
   7:     0x7043a53584d9 - <unknown>
   8:     0x7043a53584c6 - <unknown>
   9:     0x7043a4cd8062 - <unknown>
  10:     0x7043a4cd81fb - <unknown>
  11:     0x7043a4cd85b8 - <unknown>
  12:     0x7043a4f8f562 - <unknown>
  13:     0x7043a4eecf1e - <unknown>
  14:     0x7043a4e8c2ff - <unknown>
  15:     0x7043a536863e - <unknown>
  16:     0x7043a536f690 - <unknown>
  17:     0x7043a535d8e4 - <unknown>
  18:     0x7043a535d710 - <unknown>
  19:     0x7043a535a09b - <unknown>

``` 

without mTLS everything works fine

## Your wstunnel setup
Paste your logs of wstunnel, started with `--log-lvl=DEBUG`, and with the `command line used`
 - client
 ```
2024-12-14T12:33:47.151185Z  INFO wstunnel::protocols::tls::server: Loading tls certificate from "wstunnel-client-1.cert.pem"
2024-12-14T12:33:47.151401Z  INFO wstunnel::protocols::tls::server: Loading tls private key from "wstunnel-client-1.pem"
2024-12-14T12:33:47.163008Z  INFO wstunnel::tunnel::tls_reloader: Starting to watch tls certificates and private key for changes to reload them
2024-12-14T12:33:47.163213Z  INFO wstunnel: Starting wstunnel client v10.1.7
2024-12-14T12:33:47.163240Z  INFO wstunnel::protocols::udp::server: Starting UDP server listening cnx on 127.0.0.1:51820 with cnx timeout of 0s
2024-12-14T12:33:49.270613Z  INFO wstunnel::protocols::udp::server: New UDP connection from 127.0.0.1:42662
2024-12-14T12:33:49.270757Z  INFO wstunnel::protocols::tcp::server: Opening TCP connection to 194.87.44.164:443    
2024-12-14T12:33:49.270810Z DEBUG wstunnel::protocols::tcp::server: Connecting to 194.87.44.164:443
2024-12-14T12:33:49.338136Z DEBUG wstunnel::protocols::tcp::server: Connected to tcp endpoint 194.87.44.164:443, aborted all other connection attempts
2024-12-14T12:33:49.338176Z  INFO wstunnel::protocols::tls::server: Doing TLS handshake using SNI IpAddress(V4(Ipv4Addr([194, 87, 44, 164]))) with the server 194.87.44.164:443
2024-12-14T12:33:49.338199Z DEBUG rustls::client::hs: No cached session for IpAddress(V4(Ipv4Addr([194, 87, 44, 164])))    
2024-12-14T12:33:49.338389Z DEBUG rustls::client::hs: Not resuming any session    
2024-12-14T12:33:49.407227Z DEBUG rustls::client::hs: Using ciphersuite TLS13_AES_256_GCM_SHA384    
2024-12-14T12:33:49.407304Z DEBUG rustls::client::tls13: Not resuming    
2024-12-14T12:33:49.407535Z DEBUG rustls::client::tls13: TLS1.3 encrypted extensions: [Protocols([ProtocolName(687474702f312e31)])]    
2024-12-14T12:33:49.407566Z DEBUG rustls::client::hs: ALPN protocol is Some(b"http/1.1")    
2024-12-14T12:33:49.407596Z DEBUG rustls::client::tls13: Got CertificateRequest CertificateRequestPayloadTls13 { context: , extensions: [SignatureAlgorithms([ECDSA_NISTP384_SHA384, ECDSA_NISTP256_SHA256, ECDSA_NISTP521_SHA512, ED25519, RSA_PSS_SHA512, RSA_PSS_SHA384, RSA_PSS_SHA256, RSA_PKCS1_SHA512, RSA_PKCS1_SHA384, RSA_PKCS1_SHA256]), AuthorityNames([DistinguishedName(3065310b30090603550406130247423110300e06035504080c07456e676c616e64311d301b060355040a0c14777374756e6e656c20646576656c6f706d656e743125302306035504030c1c777374756e6e656c20446576656c6f706d656e7420526f6f74204341)])] }    
2024-12-14T12:33:49.407642Z DEBUG rustls::client::common: Attempting client auth    
thread 'tokio-runtime-worker' panicked at src/tunnel/transport/websocket.rs:260:37:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7043a53568aa - <unknown>
   1:     0x7043a504bc5b - <unknown>
   2:     0x7043a532bc52 - <unknown>
   3:     0x7043a5358219 - <unknown>
   4:     0x7043a5357a06 - <unknown>
   5:     0x7043a5358e11 - <unknown>
   6:     0x7043a535854a - <unknown>
   7:     0x7043a53584d9 - <unknown>
   8:     0x7043a53584c6 - <unknown>
   9:     0x7043a4cd8062 - <unknown>
  10:     0x7043a4cd81fb - <unknown>
  11:     0x7043a4cd85b8 - <unknown>
  12:     0x7043a4f8f562 - <unknown>
  13:     0x7043a4eecf1e - <unknown>
  14:     0x7043a4e8c2ff - <unknown>
  15:     0x7043a536863e - <unknown>
  16:     0x7043a536f690 - <unknown>
  17:     0x7043a535d8e4 - <unknown>
  18:     0x7043a535d710 - <unknown>
  19:     0x7043a535a09b - <unknown>
```

 - server
```
2024-12-14T12:33:22.091644Z  INFO wstunnel::protocols::tls::server: Loading tls certificate from "wstunnel-server.cert.pem"
2024-12-14T12:33:22.091802Z  INFO wstunnel::protocols::tls::server: Loading tls private key from "wstunnel-server.pem"
2024-12-14T12:33:22.091890Z  INFO wstunnel::protocols::tls::server: Loading tls certificate from "ca.cert.pem"
2024-12-14T12:33:22.092153Z  INFO wstunnel: Starting wstunnel server v10.1.7 with config WsServerConfig { socket_so_mark: None, bind: 0.0.0.0:443, websocket_ping_frequency: Some(30s), timeout_connect: 10s, websocket_mask_frame: false, restriction_config: None, tls: true, mTLS: true }
2024-12-14T12:33:22.092218Z DEBUG wstunnel: Restriction rules: RestrictionsRules {
    restrictions: [
        RestrictionConfig {
            name: "Allow All",
            match: [
                Any,
            ],
            allow: [
                Tunnel(
                    AllowTunnelConfig {
                        protocol: [],
                        port: [
                            51820..=51820,
                        ],
                        host: Regex(
                            "^localhost$",
                        ),
                        cidr: [
                            0.0.0.0/0,
                            ::/0,
                        ],
                    },
                ),
                ReverseTunnel(
                    AllowReverseTunnelConfig {
                        protocol: [],
                        port: [],
                        port_mapping: {},
                        cidr: [
                            0.0.0.0/0,
                            ::/0,
                        ],
                    },
                ),
            ],
        },
    ],
}    
2024-12-14T12:33:22.093096Z  INFO wstunnel::tunnel::server::server: Starting wstunnel server listening on 0.0.0.0:443
2024-12-14T12:33:22.093467Z  INFO wstunnel::tunnel::tls_reloader: Starting to watch tls certificates and private key for changes to reload them
2024-12-14T12:33:22.178388Z  INFO cnx{peer="185.253.180.200:9268"}: wstunnel::tunnel::server::server: Accepting connection
2024-12-14T12:33:22.178609Z  INFO cnx{peer="185.253.180.200:9268"}: wstunnel::tunnel::server::server: Doing TLS handshake
2024-12-14T12:33:22.178673Z DEBUG cnx{peer="185.253.180.200:9268"}: rustls::server::hs: decided upon suite TLS13_AES_256_GCM_SHA384    
2024-12-14T12:33:22.178892Z DEBUG cnx{peer="185.253.180.200:9268"}: rustls::server::hs: Chosen ALPN protocol [104, 116, 116, 112, 47, 49, 46, 49]    
2024-12-14T12:33:23.409797Z DEBUG cnx{peer="185.253.180.200:9268"}: rustls::common_state: Sending warning alert CloseNotify    
2024-12-14T12:33:23.410059Z ERROR cnx{peer="185.253.180.200:9268"}: wstunnel::tunnel::server::server: Error while upgrading cnx: hyper::Error(Shutdown, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
2024-12-14T12:33:49.361526Z  INFO cnx{peer="185.253.180.200:9281"}: wstunnel::tunnel::server::server: Accepting connection
2024-12-14T12:33:49.361675Z  INFO cnx{peer="185.253.180.200:9281"}: wstunnel::tunnel::server::server: Doing TLS handshake
2024-12-14T12:33:49.362006Z DEBUG cnx{peer="185.253.180.200:9281"}: rustls::server::hs: decided upon suite TLS13_AES_256_GCM_SHA384    
2024-12-14T12:33:49.362178Z DEBUG cnx{peer="185.253.180.200:9281"}: rustls::server::hs: Chosen ALPN protocol [104, 116, 116, 112, 47, 49, 46, 49]    
2024-12-14T12:33:50.593371Z DEBUG cnx{peer="185.253.180.200:9281"}: rustls::common_state: Sending warning alert CloseNotify    
2024-12-14T12:33:50.593622Z ERROR cnx{peer="185.253.180.200:9281"}: wstunnel::tunnel::server::server: Error while upgrading cnx: hyper::Error(Shutdown, Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })

```

## Desktop (please complete the following information):
 - OS: [linux amd64]
`
Ubuntu 24.04.1 LTS
Linux lutz-pc 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
`
 - Version [wstunnel 10.1.7]

**Comment by erebe** [comment] 2024-12-14 20:16
Hello,

I am going to fix the panic and update the doc, but the issue is coming from because the common name of your client certificate contains invalid URL character.
By default, if you use a client certificate, the upgrade path prefix is going to be the common name of the certificate.

So the fix is to generate a client certificate with a common name that only contains url valid characters

![image](https://github.com/user-attachments/assets/33e86743-c104-4f14-a5ea-d175aaee71dc)

**Comment by erebe** [comment] 2024-12-15 08:09
The panic is fixed in new release https://github.com/erebe/wstunnel/releases/tag/v10.1.8

**Closed** 2024-12-15 13:31 UTC
Labels: bug
